name: Deploy to Vercel

on:
  push:
    branches:
      - mainnn  # Adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (optional for specific frameworks)
      - name: Install dependencies
        run: npm install

      # Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --yes
